---
  - name: "Playing with Ansible and Git"
    hosts: localhost
    connection: local
    vars:
       private_ip: "{{ private_ip}}"


    tasks:

    - stat:
        path:  ./hosts
      register: hosts_file

    - name: create ansible host inventory file
      file:
        path: ./hosts
        state: touch
        mode: 0755
      when: not hosts_file.stat.exists

    - name: "adding private ip to host file for ansible playbook"
      blockinfile:
        path: ./hosts
        insertafter: EOF
        block: |
            [privatehost]
            {{private_ip}}
